---
title: "Olympics analysis"
author: "Tamas Nagy"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

theme_set(theme_light())

```

```{r}
# Read data
olympics <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv')

```

```{r}
olympics <-
    olympics %>% 
    mutate(bmi = weight / (height/100)^2)
```

How many olympics have been between 1896-2016?
```{r}
# Events
olympics %>% 
    distinct(games, .keep_all = TRUE) %>% 
    count(season)

# Athletes
olympics %>% 
    count(season)

# City
olympics %>% 
    distinct(games, .keep_all = TRUE) %>% 
    count(city, sort = TRUE)

```

```{r}
set.seed(123)

olympics %>% 
    drop_na(height) %>% 
    sample_n(10000) %>% 
    ggplot() +
    aes(x = year, y = height, color = sex) +
    geom_jitter(size = 1, height = 0, alpha = .5) +
    geom_smooth(method = "lm") +
    labs(x = NULL,
         y = "Height (cm)",
         title = "Height of olympic athletes over the years (10k random athletes)",
         subtitle = "Both males and females show an increase over time.")

olympics %>% 
    drop_na(height, weight) %>% 
    sample_n(10000) %>% 
    pivot_longer(cols = height:weight,
                 names_to = "variable",
                 values_to = "value") %>% 
    ggplot() +
    aes(x = year, y = value, color = sex) +
    geom_jitter(size = 1, height = 0, alpha = .5) +
    geom_smooth(method = "lm") +
    facet_wrap(~variable, 
               nrow = 2,
               scales = "free_y") +
    labs(x = NULL,
         y = "Height (cm) or Weight (kg)",
         title = "Height and weight of olympic athletes over the years (10k random athletes)",
         subtitle = "Both males and females show an increase over time.")
    

```

```{r}
olympics %>% 
    drop_na(medal, age) %>% 
    group_by(year) %>% 
    summarise(avg_age = mean(age),
              se_age = sd(age)/sqrt(n())) %>% 
    ggplot() +
    aes(x = year,
        y = avg_age,
        ymin = avg_age - se_age,
        ymax = avg_age + se_age) +
    geom_ribbon(alpha = .2) +
    geom_line(size = 1.2, color = "red")
    

```

```{r}
olympics %>% 
    distinct(year, sport) %>% 
    count(sport, sort = TRUE) %>% 
    mutate(sport = fct_reorder(sport, n)) %>% 
    ggplot() +
    aes(y = sport, x = n, fill = sport) +
    geom_col(show.legend = FALSE) +
    scale_fill_viridis_d(option = "magma") +
    labs(y = NULL,
         title = "Nr of times when sport was included",
         x = "Nr")
    

```

